### ISSUE TITLE
Spacing between Text (any font)

### ISSUE THREAD

**Issue by MorganPubblicita** [EffEPi/fabric.curvedText#15]
While I was using a script to hat uses this library as a base, I saw that the actual Curved text comes (sometimes) with a rather weird spacing. I think this is a problem related to two/three letters in particular, such as a-i-o.

I'm not a programmer myself, so I can't really help, but I still wanted to point it out.

Hoping someone will resolve this bug.

Good day.

**Comment by thisisbbc** [comment]
+1, I report this issue as well
