### ISSUE TITLE
curvedText broken with new fabric 1.5

### ISSUE THREAD

**Issue by tonycaso** [EffEPi/fabric.curvedText#18]
See your own jsfiddle and you will see it's broken now.

http://jsfiddle.net/EffEPi/qpJTz/

**Comment by daochung** [comment]
it's big problem, someone else can help?

**Comment by radykal** [comment]
asturur from fabricjs found the bug. Uncomment line 436:
`ctx.save();`
and line 468:
`ctx.restore();`

That will fix the bug with 1.6

**Comment by EffEPi** [comment]
It works now, see http://jsfiddle.net/EffEPi/qpJTz/ (it uses the very last release of fabric.js)
