### ISSUE TITLE
When change scale, it has bug.

### ISSUE THREAD

**Issue by daochung** [EffEPi/fabric.curvedText#20]
I use your demo to show you how to see it.
http://jsfiddle.net/EffEPi/qpJTz/
http://screencast.com/t/ZCnvnK7gvf

**Comment by daochung** [comment]
It has same problem when trying to export design to image. :(

**Comment by syrusbp** [comment]
Hi 

Check this https://github.com/EffEPi/fabric.curvedText/issues/22#issuecomment-150781199

**Comment by TuanLu** [comment]
@syrusbp Thank you bro :+1:

**Comment by EffEPi** [comment]
fixed with latest pull
