### ISSUE TITLE
Curved Text Effects

### ISSUE THREAD

**Issue by MULLAINATHAN** [EffEPi/fabric.curvedText#21]
Curved Text Effects :
I just try this library. It's working fine. But I can't found the solution to apply effects (curved, arc, STRAIGHT, smallToLarge, largeToSmallTop, largeToSmallBottom, bulge) to curved text. 
Please help me to solve this issue.
Thanks in advance.

**Comment by EffEPi** [comment]
You can see the example that shows all the working examples here:  http://jsfiddle.net/EffEPi/qpJTz/
