### ISSUE TITLE
Bug with Scale and CurvedText

### ISSUE THREAD

**Issue by neopheus** [EffEPi/fabric.curvedText#22]
Bug with Scale and CurvedText

1 - Open : https://jsfiddle.net/EffEPi/qpJTz/
2 - Scale the CurvedText Selection
3 - Change the Text (CurvedText)
4 - BUG : The CurvedText is in wrong position

Do you know how to fix this problem?

Thx a lot

**Comment by syrusbp** [comment]
I am also looking solution for this issue.

**Comment by Jochuaf** [comment]
Hi Effepi,
Your code works really great except this problem. Is there any solution for this problem?
Thanx in advance.

**Comment by syrusbp** [comment]
Hi 

I solved the problem.
https://jsfiddle.net/qpJTz/231/

No more problems with wrong position :+1: 
Works with fabric 1.5.0, 1.6.0 rc1

**Comment by EffEPi** [comment]
How did you solve it ? I would like to integrate it with the current version


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by syrusbp** [comment]
I noticed that the problem does not occur when we set object scaleX and scaleY  to 1 and angle to 0.

```javascript
$('#radius, #spacing, #fill').change(function(){
    //Get textCurved object
    var obj = canvas.getActiveObject(); 
    if(obj){  
        //Get actual object scaleX, scaleY, angle    
        var scaleX = obj.get('scaleX'); 
        var scaleY = obj.get('scaleY'); 
        var angle = obj.get('angle'); 
           
        //Set actual object scaleX, scaleY to 1 and angle to 0
        obj.set('scaleX', 1); 
        obj.set('scaleY', 1); 
        obj.set('angle', 0); 
        
        //Set radius, scale, fill, etc. to expected value
        obj.set($(this).attr('id'),$(this).val()); 
        
        //At the end, set object to previous values 
        obj.set('scaleX', scaleX);
        obj.set('scaleY', scaleY);
        obj.set('angle', angle);
    }
    canvas.renderAll();
});
```

Voilà coords are OK :)

**Comment by EffEPi** [comment]
fixed with latest pull
