### ISSUE TITLE
Compatible with fabricjs 2.x

### ISSUE THREAD

**Issue by hary28** [EffEPi/fabric.curvedText#40]
Is the planned library update for fabricjs 2.x?

**Comment by dragondgold** [comment]
I also want to use this library on fabric.js 2.0. I probably will be porting it in the next few days and will make a pull request

**Comment by dragondgold** [comment]
I made some modifications for it to work on fabricjs 2.x [here](https://github.com/dragondgold/fabric.curvedText). The only thing that is not working is the save/load feature that does work on previous versions.

**Comment by suathh** [comment]
Hello, thanks for great work. I am trying to add curvedText feature to my project which contains fabric.js v2.0.0 but it is giving me `Uncaught TypeError: Cannot set property 'backgroundColor' of undefined
    at fabric.curvedText.js:39`

It is working fine with  fabric.js v1.7.22 and also working fine with v2.0.0-beta1

I inspected @dragondgold 's https://github.com/EffEPi/fabric.curvedText/pull/41 pull request but still couldn't find the problem for me.

Also related with this issue #43

**Comment by ghost** [comment]
I'm having the same problem after updating to fabricjs v2.0.1
